# Generated by Django 3.0.2 on 2020-11-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquariform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobiles', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateField()),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
