# Generated by Django 3.0.2 on 2020-11-13 18:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_auto_20201113_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquariform',
            name='cources',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('python', 'PYTHON'), ('django', 'DJANGO'), ('ui', 'UI'), ('flask', 'FLASK'), ('java', 'JAVA')], default='python', max_length=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquariform',
            name='location',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ameerpet', 'AMEERPET'), ('secundrabaad', 'SECANDRABAAD'), ('hyd', 'HYD'), ('begumpet', 'BEGUMPET')], default='NARAYANA', max_length=34),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquariform',
            name='shift',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('morning', 'MORNING'), ('evening', 'EVENING'), ('night', 'NIGHT')], default='MORNING', max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquariform',
            name='trainer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('narayana', 'NARAYANA'), ('srinivas', 'SRINIVAS'), ('rubi', 'RUBI'), ('rachna', 'RACHNA'), ('mohit', 'MOHIT')], default='AMEERPET', max_length=35),
            preserve_default=False,
        ),
    ]
