# Generated by Django 3.0.2 on 2020-11-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0007_auto_20201113_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquariform',
            name='mobiles',
            field=models.BigIntegerField(),
        ),
    ]
