# Generated by Django 3.0.2 on 2020-11-13 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_auto_20201113_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquariform',
            name='date',
        ),
    ]
