# Generated by Django 3.0.2 on 2020-11-13 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_remove_enquariform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquariform',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
