# Generated by Django 3.0.2 on 2020-11-15 15:31

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_enquariform_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('salary', models.IntegerField()),
                ('qualification', multiselectfield.db.fields.MultiSelectField(choices=[('ba', 'BA'), ('be', 'BE'), ('bsc', 'BSC'), ('bcom', 'BCOM'), ('c-cat', 'C-CAT')], max_length=20)),
            ],
        ),
    ]
