# Generated by Django 3.0.2 on 2020-11-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0012_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('telugu', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('english', models.IntegerField()),
                ('math', models.IntegerField()),
            ],
        ),
    ]
